/**
 * specs/batch-002.ts — the fill-out-to-90 batch.
 *
 * Uses the new templates (BeforeAfter, StatementStack, DashboardShowcase) as
 * well as more CallFlow / KineticStatement / ProductDemo variants across
 * industries and word pairings. Two guardrails from CLAUDE.md observed here:
 *   - NO pricing numbers on-screen (§1 — unconfirmed).
 *   - NO competitor names, per memory.
 * And house style: no em-dashes in on-screen copy (§9).
 *
 * IDs start at reel-100 to leave headroom below for verification specs.
 */

import { ReelSpec } from './schema';

// ────────────────────────────────────────────────────────────────────────────
// CALLFLOW — 7 new industry variants (existing batch already has 7)
// ────────────────────────────────────────────────────────────────────────────
const CALLFLOW_BATCH: ReelSpec[] = [
  {
    id: 'reel-100-callflow-electrician',
    seed: 100100,
    template: 'CallFlow',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand. Your client. Real revenue.',
      callFlow: {
        businessName: 'Volt & Wire Electric',
        callerName: 'Kevin Ortiz',
        callerPhone: '(555) 429-8106',
        callerAddress: '3204 Aspen Street',
        priority: 'High',
        summary:
          'Kevin Ortiz called about a tripped breaker with no power to half the house. The AI dispatched an electrician for today at 5:30 PM and texted a safety checklist.',
        smsApp: 'MESSAGES',
        smsBody:
          'New emergency call — Kevin Ortiz, half-house outage, today 5:30 PM. Safety checklist sent.',
      },
      captions: [
        { text: 'A no-power call hits the line.',            inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI answers in one ring.',              inFrame: 110, outFrame: 200, emphasis: [] },
        { text: 'It logs the fault. Books the visit.',       inFrame: 235, outFrame: 590, emphasis: ['books'] },
        { text: 'Owner sees the booking as a text.',         inFrame: 660, outFrame: 770, emphasis: ['text'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — electrician emergency.',
  },
  {
    id: 'reel-101-callflow-locksmith',
    seed: 101101,
    template: 'CallFlow',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Same platform. Every industry.',
      callFlow: {
        businessName: 'KeyStone Locksmith',
        callerName: 'Amber Chen',
        callerPhone: '(555) 617-3388',
        callerAddress: '48 Willow Court',
        priority: 'High',
        summary:
          "Amber Chen is locked out of her home at 48 Willow Court. The AI dispatched a locksmith with a 25-minute ETA and texted the arrival window.",
        smsApp: 'MESSAGES',
        smsBody:
          'New lockout call — Amber Chen, home, 48 Willow Court. Tech dispatched, ETA 25 min.',
      },
      captions: [
        { text: 'A lockout call comes in.',                  inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI picks up before they can hang up.', inFrame: 110, outFrame: 200, emphasis: [] },
        { text: 'It captures the address. Dispatches a tech.', inFrame: 235, outFrame: 590, emphasis: ['dispatches'] },
        { text: 'Owner gets the win as a text.',              inFrame: 660, outFrame: 770, emphasis: ['text'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — locksmith lockout.',
  },
  {
    id: 'reel-102-callflow-chiro',
    seed: 102102,
    template: 'CallFlow',
    mode: 'light',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label. Your brand on every touchpoint.',
      callFlow: {
        businessName: 'Align Chiropractic',
        callerName: 'Nathan Reyes',
        callerPhone: '(555) 208-1495',
        callerAddress: 'New patient consult',
        priority: 'Normal',
        summary:
          'Nathan Reyes called for a new-patient consult after a car accident. The AI booked a Thursday 11:00 AM slot and texted the intake form.',
        smsApp: 'MESSAGES',
        smsBody:
          'New patient — Nathan Reyes, post-accident consult, Thursday 11:00 AM. Intake form sent.',
      },
      captions: [
        { text: 'A new patient calls in.',                    inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI takes it. Books the consult.',       inFrame: 110, outFrame: 200, emphasis: ['books'] },
        { text: 'It sends the intake. Confirms by text.',     inFrame: 235, outFrame: 590, emphasis: [] },
        { text: 'Owner sees the booking land.',                inFrame: 660, outFrame: 770, emphasis: ['booking'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — chiropractor consult, LIGHT mode.',
  },
  {
    id: 'reel-103-callflow-dental',
    seed: 103103,
    template: 'CallFlow',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every industry. Every client. Same platform.',
      callFlow: {
        businessName: 'Bright Smile Dental',
        callerName: 'Priya Kapoor',
        callerPhone: '(555) 471-2263',
        callerAddress: 'Cleaning + exam',
        priority: 'Normal',
        summary:
          'Priya Kapoor called to schedule a cleaning and exam. The AI booked a Tuesday 8:30 AM slot and texted directions and insurance details.',
        smsApp: 'MESSAGES',
        smsBody:
          'New booking — Priya Kapoor, cleaning + exam, Tuesday 8:30 AM. Insurance details on file.',
      },
      captions: [
        { text: 'A cleaning call comes in.',                  inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI books it. In one ring.',              inFrame: 110, outFrame: 200, emphasis: [] },
        { text: 'It handles the insurance question too.',      inFrame: 235, outFrame: 590, emphasis: [] },
        { text: 'Owner sees the booking as a text.',            inFrame: 660, outFrame: 770, emphasis: ['text'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — dental cleaning booking.',
  },
  {
    id: 'reel-104-callflow-salon',
    seed: 104104,
    template: 'CallFlow',
    mode: 'light',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label. Sold under your name.',
      callFlow: {
        businessName: 'Rio Blowout Bar',
        callerName: 'Taylor Nguyen',
        callerPhone: '(555) 336-8842',
        callerAddress: 'Cut + color booking',
        priority: 'Normal',
        summary:
          'Taylor Nguyen called for a cut and color with a specific stylist. The AI matched the stylist and booked a Saturday 12:00 PM slot.',
        smsApp: 'MESSAGES',
        smsBody:
          'New booking — Taylor Nguyen, cut + color with Rio, Saturday 12:00 PM. Confirmation sent.',
      },
      captions: [
        { text: 'A stylist request comes in.',                inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI matches the request. Books it.',      inFrame: 110, outFrame: 200, emphasis: ['matches'] },
        { text: 'It confirms the time. Sends the reminder.',    inFrame: 235, outFrame: 590, emphasis: [] },
        { text: 'Owner sees the booking land.',                 inFrame: 660, outFrame: 770, emphasis: ['booking'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — salon booking, LIGHT.',
  },
  {
    id: 'reel-105-callflow-landscaping',
    seed: 105105,
    template: 'CallFlow',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Sold by you. Answered by AI.',
      callFlow: {
        businessName: 'Evergreen Landscape Co.',
        callerName: 'Grace Kwon',
        callerPhone: '(555) 907-1220',
        callerAddress: '7115 Birch Lane',
        priority: 'Normal',
        summary:
          'Grace Kwon requested a quote for weekly lawn maintenance. The AI captured the lot size, booked an on-site walk-through for Friday 9:30 AM, and texted a price range.',
        smsApp: 'MESSAGES',
        smsBody:
          'New quote — Grace Kwon, weekly maintenance, Friday 9:30 AM walk-through. Price range sent.',
      },
      captions: [
        { text: 'A recurring-service lead calls in.',          inFrame: 28, outFrame: 84,  emphasis: ['recurring'] },
        { text: 'Your AI logs the lot. Books the visit.',       inFrame: 110, outFrame: 200, emphasis: [] },
        { text: 'It sends a price range on the way out.',        inFrame: 235, outFrame: 590, emphasis: [] },
        { text: 'Owner gets the lead by text.',                  inFrame: 660, outFrame: 770, emphasis: ['lead'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — landscaping quote.',
  },
  {
    id: 'reel-106-callflow-pest',
    seed: 106106,
    template: 'CallFlow',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand. Every kind of business.',
      callFlow: {
        businessName: 'ShieldGuard Pest Control',
        callerName: 'Omar Haddad',
        callerPhone: '(555) 550-7734',
        callerAddress: '1902 Chestnut Way',
        priority: 'High',
        summary:
          'Omar Haddad reported an active wasp nest by his front door. The AI booked a same-day tech visit at 2:00 PM and texted safety instructions.',
        smsApp: 'MESSAGES',
        smsBody:
          'New same-day — Omar Haddad, active wasp nest, today 2:00 PM. Safety notes sent.',
      },
      captions: [
        { text: 'An urgent call hits the line.',              inFrame: 28, outFrame: 84,  emphasis: [] },
        { text: 'Your AI answers. Books the same-day.',        inFrame: 110, outFrame: 200, emphasis: ['same-day'] },
        { text: 'It sends the safety notes automatically.',     inFrame: 235, outFrame: 590, emphasis: [] },
        { text: 'Owner sees the win as a text.',                inFrame: 660, outFrame: 770, emphasis: ['text'] },
      ],
    },
    cta: 'Start your agency',
    notes: 'CallFlow — pest control same-day.',
  },
];

// ────────────────────────────────────────────────────────────────────────────
// BEFOREAFTER — 17 new comparison reels across industries + word pairings
// ────────────────────────────────────────────────────────────────────────────

const BA_WORD_PAIRS = [
  { before: 'MISSED.',   after: 'ANSWERED.' },
  { before: 'GONE.',     after: 'CAPTURED.' },
  { before: 'LOST.',     after: 'KEPT.' },
  { before: 'IGNORED.',  after: 'HANDLED.' },
  { before: 'DROPPED.',  after: 'BOOKED.' },
  { before: 'SILENT.',   after: 'LIVE.' },
  { before: 'NOTHING.',  after: 'EVERYTHING.' },
] as const;

const BEFOREAFTER_BATCH: ReelSpec[] = [
  {
    id: 'reel-120-ba-hvac',
    seed: 120120,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every industry. Same platform.',
      beforeAfter: {
        businessName: 'AAA Heating & Cooling',
        callerName: 'Sarah Mitchell',
        callerPhone: '(555) 614-0288',
        aftermath: 'Captured. Booked. Dispatched.',
        beforeWord: BA_WORD_PAIRS[1].before,
        afterWord: BA_WORD_PAIRS[1].after,
        missedAt: '11:32 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-121-ba-auto',
    seed: 121121,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand. Sold to every trade.',
      beforeAfter: {
        businessName: "Mike's Auto Repair",
        callerName: 'David Park',
        callerPhone: '(555) 703-1149',
        aftermath: 'Tow sent. Work order opened.',
        beforeWord: BA_WORD_PAIRS[0].before,
        afterWord: BA_WORD_PAIRS[0].after,
        missedAt: '9:14 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-122-ba-electrician',
    seed: 122122,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand. Your client. Your check.',
      beforeAfter: {
        businessName: 'Volt & Wire Electric',
        callerName: 'Kevin Ortiz',
        callerPhone: '(555) 429-8106',
        aftermath: 'Emergency booked in one ring.',
        beforeWord: BA_WORD_PAIRS[2].before,
        afterWord: BA_WORD_PAIRS[2].after,
        missedAt: '6:04 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-123-ba-roofing',
    seed: 123123,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Sold by you. Answered by the AI.',
      beforeAfter: {
        businessName: 'TopShelf Roofing',
        callerName: 'Lisa Hernandez',
        callerPhone: '(555) 942-6037',
        aftermath: 'Estimate booked. Notes sent.',
        beforeWord: BA_WORD_PAIRS[3].before,
        afterWord: BA_WORD_PAIRS[3].after,
        missedAt: '3:47 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-124-ba-medspa',
    seed: 124124,
    template: 'BeforeAfter',
    mode: 'light',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label everything. Keep the margin.',
      beforeAfter: {
        businessName: 'Glow Aesthetics',
        callerName: 'Jessica Lee',
        callerPhone: '(555) 488-2261',
        aftermath: 'Consult booked. Intake sent.',
        beforeWord: BA_WORD_PAIRS[4].before,
        afterWord: BA_WORD_PAIRS[4].after,
        missedAt: '1:19 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-125-ba-vet',
    seed: 125125,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'tron',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every business. Every industry.',
      beforeAfter: {
        businessName: 'Pawsitive Pet Hospital',
        callerName: 'Marcus Brown',
        callerPhone: '(555) 226-4081',
        aftermath: 'Same-day slot booked.',
        beforeWord: BA_WORD_PAIRS[5].before,
        afterWord: BA_WORD_PAIRS[5].after,
        missedAt: '10:52 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-126-ba-cleaning',
    seed: 126126,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Set up by Sunday. Selling by Monday.',
      beforeAfter: {
        businessName: 'Sparkle Clean Co.',
        callerName: 'Rachel Davis',
        callerPhone: '(555) 318-9047',
        aftermath: 'Walk-through booked. Quote sent.',
        beforeWord: BA_WORD_PAIRS[6].before,
        afterWord: BA_WORD_PAIRS[6].after,
        missedAt: '2:08 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-127-ba-locksmith',
    seed: 127127,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'One platform. Every trade. Your brand.',
      beforeAfter: {
        businessName: 'KeyStone Locksmith',
        callerName: 'Amber Chen',
        callerPhone: '(555) 617-3388',
        aftermath: 'Tech dispatched. ETA sent.',
        beforeWord: BA_WORD_PAIRS[0].before,
        afterWord: BA_WORD_PAIRS[0].after,
        missedAt: '8:41 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-128-ba-plumbing-2',
    seed: 128128,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'This is the difference AI makes.',
      beforeAfter: {
        businessName: 'PipeRight Plumbing',
        callerName: 'Nina Alvarez',
        callerPhone: '(555) 812-7509',
        aftermath: 'Emergency slot booked. Text confirmed.',
        beforeWord: BA_WORD_PAIRS[1].before,
        afterWord: BA_WORD_PAIRS[1].after,
        missedAt: '7:29 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-129-ba-chiro',
    seed: 129129,
    template: 'BeforeAfter',
    mode: 'light',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label AI. Sold under your name.',
      beforeAfter: {
        businessName: 'Align Chiropractic',
        callerName: 'Nathan Reyes',
        callerPhone: '(555) 208-1495',
        aftermath: 'Consult booked. Intake sent.',
        beforeWord: BA_WORD_PAIRS[2].before,
        afterWord: BA_WORD_PAIRS[2].after,
        missedAt: '4:03 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-130-ba-dental',
    seed: 130130,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Local businesses. Recurring revenue. Your agency.',
      beforeAfter: {
        businessName: 'Bright Smile Dental',
        callerName: 'Priya Kapoor',
        callerPhone: '(555) 471-2263',
        aftermath: 'Cleaning booked. Reminder queued.',
        beforeWord: BA_WORD_PAIRS[3].before,
        afterWord: BA_WORD_PAIRS[3].after,
        missedAt: '12:04 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-131-ba-salon',
    seed: 131131,
    template: 'BeforeAfter',
    mode: 'light',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your logo. Your dashboard. Your check.',
      beforeAfter: {
        businessName: 'Rio Blowout Bar',
        callerName: 'Taylor Nguyen',
        callerPhone: '(555) 336-8842',
        aftermath: 'Stylist matched. Slot booked.',
        beforeWord: BA_WORD_PAIRS[4].before,
        afterWord: BA_WORD_PAIRS[4].after,
        missedAt: '5:22 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-132-ba-garagedoor',
    seed: 132132,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every trade. Every call. Every dollar.',
      beforeAfter: {
        businessName: 'OverHead Garage Doors',
        callerName: 'Brian Foster',
        callerPhone: '(555) 762-4415',
        aftermath: 'Tech dispatched. ETA sent.',
        beforeWord: BA_WORD_PAIRS[5].before,
        afterWord: BA_WORD_PAIRS[5].after,
        missedAt: '9:58 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-133-ba-handyman',
    seed: 133133,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Not a course. A platform.',
      beforeAfter: {
        businessName: 'FixIt Handyman',
        callerName: 'Jordan Mills',
        callerPhone: '(555) 191-8074',
        aftermath: 'Job scoped. Visit booked.',
        beforeWord: BA_WORD_PAIRS[6].before,
        afterWord: BA_WORD_PAIRS[6].after,
        missedAt: '11:47 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-134-ba-painting',
    seed: 134134,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label. Full stack. Sold by you.',
      beforeAfter: {
        businessName: 'BrushWorks Painting',
        callerName: 'Eleanor Diaz',
        callerPhone: '(555) 502-3390',
        aftermath: 'Estimate booked. Portfolio sent.',
        beforeWord: BA_WORD_PAIRS[0].before,
        afterWord: BA_WORD_PAIRS[0].after,
        missedAt: '3:11 PM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-135-ba-pool',
    seed: 135135,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your client. Your close. Your check.',
      beforeAfter: {
        businessName: 'BlueWave Pool Service',
        callerName: 'Christina Wu',
        callerPhone: '(555) 288-6613',
        aftermath: 'Weekly service booked. Route added.',
        beforeWord: BA_WORD_PAIRS[1].before,
        afterWord: BA_WORD_PAIRS[1].after,
        missedAt: '10:14 AM',
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-136-ba-tree',
    seed: 136136,
    template: 'BeforeAfter',
    mode: 'dark',
    background: 'tron',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Sell the AI. Skip the code.',
      beforeAfter: {
        businessName: 'CedarLine Tree Care',
        callerName: 'Mark Sullivan',
        callerPhone: '(555) 476-1928',
        aftermath: 'Inspection booked. Notes sent.',
        beforeWord: BA_WORD_PAIRS[2].before,
        afterWord: BA_WORD_PAIRS[2].after,
        missedAt: '4:31 PM',
      },
    },
    cta: 'Start your agency',
  },
];

// ────────────────────────────────────────────────────────────────────────────
// DASHBOARDSHOWCASE — 17 new variants across brands + call/lead surfaces
// ────────────────────────────────────────────────────────────────────────────
const DASHBOARD_BATCH: ReelSpec[] = [
  {
    id: 'reel-140-dash-hvac',
    seed: 140140,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every client. Every call. In one place.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Rivertown Digital',
        headline: 'CLIENT CALLS. YOUR DASHBOARD.',
        rows: [
          { primary: 'Sarah Mitchell', secondary: 'Furnace down · dispatched 11 AM',   meta: '2:14', status: 'booked', atFrame: 20  },
          { primary: 'David Park',      secondary: 'Roadside · tow ETA 35 min',        meta: '1:48', status: 'lead',   atFrame: 120 },
          { primary: 'Lisa Hernandez',  secondary: 'Wind damage estimate · Fri 1 PM',  meta: '2:32', status: 'booked', atFrame: 220 },
          { primary: 'Nathan Reyes',    secondary: 'New patient consult · Thu 11 AM',  meta: '1:12', status: 'booked', atFrame: 340 },
          { primary: 'Omar Haddad',      secondary: 'Wasp nest · today 2 PM',           meta: '2:04', status: 'booked', atFrame: 460 },
          { primary: 'Kevin Ortiz',     secondary: 'Half-house outage · 5:30 PM',       meta: '0:58', status: 'lead',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-141-dash-leads',
    seed: 141141,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every lead. Sorted. In your dashboard.',
      dashboardShowcase: {
        variant: 'leads',
        surfaceLabel: 'Leads Inbox',
        brandName: 'Coastline Growth',
        headline: 'LEADS IN. SORTED FOR YOU.',
        rows: [
          { primary: 'BlueWave Pool Service',   secondary: 'Pool cleaning',       meta: 'Austin, TX',  status: 'new',       atFrame: 20  },
          { primary: 'CedarLine Tree Care',      secondary: 'Tree removal',        meta: 'Denver, CO',   status: 'new',       atFrame: 120 },
          { primary: 'BrushWorks Painting',      secondary: 'Interior painting',   meta: 'Nashville, TN', status: 'contacted', atFrame: 220 },
          { primary: 'FixIt Handyman',           secondary: 'General repair',       meta: 'Portland, OR', status: 'new',       atFrame: 340 },
          { primary: 'OverHead Garage Doors',    secondary: 'Garage repair',        meta: 'Phoenix, AZ',   status: 'contacted', atFrame: 460 },
          { primary: 'Rio Blowout Bar',           secondary: 'Salon',               meta: 'Miami, FL',    status: 'new',       atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-142-dash-white-label',
    seed: 142142,
    template: 'DashboardShowcase',
    mode: 'light',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand on every screen. Every client.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'North Star Studios',
        headline: 'YOUR LOGO. YOUR CLIENT.',
        rows: [
          { primary: 'Priya Kapoor',    secondary: 'Cleaning booked · Tuesday 8:30 AM',  meta: '1:41', status: 'booked', atFrame: 20  },
          { primary: 'Jessica Lee',      secondary: 'Botox consult · Thursday 4:30 PM',   meta: '1:19', status: 'booked', atFrame: 120 },
          { primary: 'Marcus Brown',     secondary: 'Same-day urgent · 3:15 PM',           meta: '2:07', status: 'booked', atFrame: 220 },
          { primary: 'Rachel Davis',     secondary: 'Recurring cleaning · Sat 10 AM',      meta: '1:22', status: 'lead',   atFrame: 340 },
          { primary: 'Amber Chen',       secondary: 'Lockout dispatched · 25 min ETA',      meta: '0:48', status: 'booked', atFrame: 460 },
          { primary: 'Taylor Nguyen',    secondary: 'Stylist request · Saturday 12 PM',     meta: '1:04', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-143-dash-agency',
    seed: 143143,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every client. Every industry. One dashboard.',
      dashboardShowcase: {
        variant: 'leads',
        surfaceLabel: 'Leads Inbox',
        brandName: 'Peak Local Digital',
        headline: 'INBOUND LEADS. YOUR STACK.',
        rows: [
          { primary: 'Align Chiropractic',      secondary: 'Chiropractic',       meta: 'Boise, ID',      status: 'new',       atFrame: 20  },
          { primary: 'Volt & Wire Electric',    secondary: 'Electrician',         meta: 'Chicago, IL',    status: 'contacted', atFrame: 120 },
          { primary: 'KeyStone Locksmith',      secondary: 'Locksmith',           meta: 'Seattle, WA',    status: 'new',       atFrame: 220 },
          { primary: 'Pawsitive Pet Hospital',  secondary: 'Veterinary',           meta: 'Charlotte, NC',  status: 'new',       atFrame: 340 },
          { primary: 'Evergreen Landscape Co.', secondary: 'Landscaping',          meta: 'Sacramento, CA', status: 'contacted', atFrame: 460 },
          { primary: 'ShieldGuard Pest Control', secondary: 'Pest control',        meta: 'Tampa, FL',      status: 'new',       atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-144-dash-hvac-heavy',
    seed: 144144,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'One brand. Every touchpoint. Every dollar.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'AAA Heating & Cooling',
        headline: 'WHITE-LABEL. YOUR CLIENT.',
        rows: [
          { primary: 'Sarah Mitchell', secondary: 'No-heat call · dispatched today', meta: '2:14', status: 'booked', atFrame: 20  },
          { primary: 'Nina Alvarez',    secondary: 'Frozen pipe · same-day 7 PM',      meta: '1:38', status: 'booked', atFrame: 120 },
          { primary: 'Grace Kwon',      secondary: 'Filter service · weekly plan',      meta: '1:12', status: 'lead',   atFrame: 220 },
          { primary: 'Brian Foster',    secondary: 'AC not cooling · tomorrow 10 AM',   meta: '2:04', status: 'booked', atFrame: 340 },
          { primary: 'Christina Wu',    secondary: 'New install estimate · Fri 3 PM',   meta: '2:31', status: 'lead',   atFrame: 460 },
          { primary: 'Jordan Mills',    secondary: 'Heat pump service · Mon 9 AM',      meta: '0:56', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-145-dash-medical',
    seed: 145145,
    template: 'DashboardShowcase',
    mode: 'light',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your client. Your dashboard. Every month.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Glow Aesthetics',
        headline: 'EVERY CONSULT. CAPTURED.',
        rows: [
          { primary: 'Jessica Lee',   secondary: 'Botox consult · Thursday 4:30 PM',   meta: '1:19', status: 'booked', atFrame: 20  },
          { primary: 'Nathan Reyes',   secondary: 'New patient consult · Thu 11 AM',    meta: '1:12', status: 'booked', atFrame: 120 },
          { primary: 'Priya Kapoor',   secondary: 'Follow-up · Tuesday 3 PM',            meta: '0:52', status: 'booked', atFrame: 220 },
          { primary: 'Eleanor Diaz',    secondary: 'First-time consult · Fri 10 AM',      meta: '1:44', status: 'lead',   atFrame: 340 },
          { primary: 'Taylor Nguyen',   secondary: 'Rescheduling · confirmed Sat',        meta: '0:38', status: 'booked', atFrame: 460 },
          { primary: 'Christina Wu',   secondary: 'New service inquiry · info sent',      meta: '1:04', status: 'lead',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-146-dash-trades',
    seed: 146146,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'tron',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Sold by you. Answered by AI.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'BlueCollar Digital',
        headline: 'TRADE CALLS. HANDLED.',
        rows: [
          { primary: 'Kevin Ortiz',      secondary: 'Half-house outage · 5:30 PM',    meta: '1:58', status: 'booked', atFrame: 20  },
          { primary: 'Brian Foster',     secondary: 'Garage repair · today 10 AM',      meta: '1:12', status: 'booked', atFrame: 120 },
          { primary: 'Nina Alvarez',     secondary: 'Frozen pipe · same-day 7 PM',      meta: '2:04', status: 'booked', atFrame: 220 },
          { primary: 'Mark Sullivan',    secondary: 'Tree removal estimate · Fri',      meta: '1:33', status: 'lead',   atFrame: 340 },
          { primary: 'Omar Haddad',      secondary: 'Wasp nest · today 2 PM',            meta: '0:47', status: 'booked', atFrame: 460 },
          { primary: 'David Park',       secondary: 'Roadside · tow ETA 35 min',         meta: '2:22', status: 'lead',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-147-dash-leads2',
    seed: 147147,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Local businesses. Recurring revenue.',
      dashboardShowcase: {
        variant: 'leads',
        surfaceLabel: 'Leads Inbox',
        brandName: 'Cascade Local',
        headline: 'FRESH LEADS. EVERY DAY.',
        rows: [
          { primary: 'Sparkle Clean Co.',        secondary: 'Recurring cleaning',   meta: 'Portland, OR', status: 'new',       atFrame: 20  },
          { primary: 'Bright Smile Dental',      secondary: 'Dental practice',       meta: 'Bend, OR',      status: 'contacted', atFrame: 120 },
          { primary: 'Rio Blowout Bar',           secondary: 'Hair salon',           meta: 'Salem, OR',     status: 'new',       atFrame: 220 },
          { primary: 'PipeRight Plumbing',       secondary: 'Plumbing',              meta: 'Eugene, OR',    status: 'new',       atFrame: 340 },
          { primary: "Mike's Auto Repair",        secondary: 'Auto shop',            meta: 'Hillsboro, OR', status: 'contacted', atFrame: 460 },
          { primary: 'CedarLine Tree Care',      secondary: 'Tree service',          meta: 'Gresham, OR',   status: 'new',       atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-148-dash-vet-multi',
    seed: 148148,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every booking. Every text. In one place.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Pawsitive Pet Hospital',
        headline: 'EVERY PET. CAPTURED.',
        rows: [
          { primary: 'Marcus Brown',   secondary: 'Same-day urgent · 3:15 PM',    meta: '2:07', status: 'booked', atFrame: 20  },
          { primary: 'Jordan Mills',   secondary: 'Vaccination visit · Sat 11 AM',  meta: '0:48', status: 'booked', atFrame: 120 },
          { primary: 'Amber Chen',      secondary: 'New patient intake · Wed 2 PM',   meta: '1:33', status: 'booked', atFrame: 220 },
          { primary: 'Nathan Reyes',    secondary: 'Rescheduling · confirmed Fri',    meta: '0:38', status: 'info',   atFrame: 340 },
          { primary: 'Grace Kwon',      secondary: 'Boarding inquiry · info sent',     meta: '1:12', status: 'lead',   atFrame: 460 },
          { primary: 'Eleanor Diaz',    secondary: 'Prescription refill · queued',     meta: '0:44', status: 'info',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-149-dash-cleaning-brand',
    seed: 149149,
    template: 'DashboardShowcase',
    mode: 'light',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label. Sold under your name.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Sparkle Clean Co.',
        headline: 'RECURRING REVENUE. LOGGED.',
        rows: [
          { primary: 'Rachel Davis',     secondary: 'Weekly booking · Saturday 10 AM',   meta: '1:22', status: 'booked', atFrame: 20  },
          { primary: 'Christina Wu',     secondary: 'One-time deep clean · Fri 9 AM',    meta: '1:48', status: 'booked', atFrame: 120 },
          { primary: 'Grace Kwon',       secondary: 'Recurring quote request · sent',    meta: '2:12', status: 'lead',   atFrame: 220 },
          { primary: 'Eleanor Diaz',      secondary: 'Move-out clean · Mon 3 PM',          meta: '1:02', status: 'booked', atFrame: 340 },
          { primary: 'Priya Kapoor',      secondary: 'Bi-weekly booking · Wed 11 AM',      meta: '0:56', status: 'booked', atFrame: 460 },
          { primary: 'Taylor Nguyen',    secondary: 'Recurring inquiry · info sent',        meta: '1:12', status: 'lead',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-150-dash-multi',
    seed: 150150,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'One agency. Every industry. Every check.',
      dashboardShowcase: {
        variant: 'leads',
        surfaceLabel: 'Leads Inbox',
        brandName: 'Signal Local Growth',
        headline: 'YOUR PIPELINE. LIVE.',
        rows: [
          { primary: 'Riverside Plumbing',      secondary: 'Plumbing',         meta: 'Austin, TX',    status: 'new',       atFrame: 20  },
          { primary: 'AAA Heating & Cooling',   secondary: 'HVAC',             meta: 'Dallas, TX',    status: 'contacted', atFrame: 120 },
          { primary: 'TopShelf Roofing',        secondary: 'Roofing',          meta: 'San Antonio, TX', status: 'new',    atFrame: 220 },
          { primary: 'Bright Smile Dental',     secondary: 'Dental',           meta: 'Houston, TX',   status: 'new',       atFrame: 340 },
          { primary: 'Pawsitive Pet Hospital',  secondary: 'Veterinary',       meta: 'Fort Worth, TX', status: 'contacted', atFrame: 460 },
          { primary: 'Evergreen Landscape Co.', secondary: 'Landscaping',      meta: 'El Paso, TX',   status: 'new',       atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-151-dash-fastagency',
    seed: 151151,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Set up by Sunday. Selling by Monday.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Blackstone Local',
        headline: 'CALLS IN. BOOKINGS OUT.',
        rows: [
          { primary: 'Kevin Ortiz',    secondary: 'Emergency electrical · today 5:30 PM', meta: '1:58', status: 'booked', atFrame: 20  },
          { primary: 'Nina Alvarez',   secondary: 'Frozen pipe · same-day 7 PM',           meta: '2:04', status: 'booked', atFrame: 120 },
          { primary: 'Mark Sullivan',   secondary: 'Tree work estimate · Fri',              meta: '1:33', status: 'lead',   atFrame: 220 },
          { primary: 'Rachel Davis',   secondary: 'Recurring cleaning · Sat 10 AM',         meta: '1:22', status: 'booked', atFrame: 340 },
          { primary: 'Grace Kwon',     secondary: 'Lawn care quote · walk-through Fri',      meta: '1:48', status: 'lead',   atFrame: 460 },
          { primary: 'Marcus Brown',   secondary: 'Vet urgent · today 3:15 PM',              meta: '0:52', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-152-dash-leads-nation',
    seed: 152152,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'tron',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Every lead. Sorted. Ready to sell.',
      dashboardShowcase: {
        variant: 'leads',
        surfaceLabel: 'Leads Inbox',
        brandName: 'Redwood Growth Co.',
        headline: 'LEADS SORTED FOR YOU.',
        rows: [
          { primary: "Mike's Auto Repair",       secondary: 'Auto shop',           meta: 'Oakland, CA',  status: 'new',       atFrame: 20  },
          { primary: 'BrushWorks Painting',      secondary: 'Painting',            meta: 'San Jose, CA',  status: 'contacted', atFrame: 120 },
          { primary: 'ShieldGuard Pest Control', secondary: 'Pest control',        meta: 'Fresno, CA',    status: 'new',       atFrame: 220 },
          { primary: 'FixIt Handyman',           secondary: 'Handyman',            meta: 'Long Beach, CA', status: 'new',      atFrame: 340 },
          { primary: 'OverHead Garage Doors',    secondary: 'Garage doors',        meta: 'Anaheim, CA',   status: 'contacted', atFrame: 460 },
          { primary: 'BlueWave Pool Service',    secondary: 'Pool service',        meta: 'Irvine, CA',    status: 'new',       atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-153-dash-roofing-brand',
    seed: 153153,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'One platform. Every trade. Every check.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'TopShelf Roofing',
        headline: 'STORM CALLS. CAPTURED.',
        rows: [
          { primary: 'Lisa Hernandez',   secondary: 'Wind damage estimate · Fri 1 PM',   meta: '2:32', status: 'booked', atFrame: 20  },
          { primary: 'Brian Foster',     secondary: 'Roof leak inspection · today 3 PM',  meta: '1:48', status: 'booked', atFrame: 120 },
          { primary: 'Christina Wu',     secondary: 'Full replacement quote · Fri 3 PM',   meta: '2:04', status: 'lead',   atFrame: 220 },
          { primary: 'Mark Sullivan',    secondary: 'Gutter repair · Mon 10 AM',            meta: '1:12', status: 'booked', atFrame: 340 },
          { primary: 'Priya Kapoor',      secondary: 'New quote request · info sent',        meta: '1:22', status: 'lead',   atFrame: 460 },
          { primary: 'Jordan Mills',     secondary: 'Shingle replacement · Thu 9 AM',        meta: '0:58', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-154-dash-salon-brand',
    seed: 154154,
    template: 'DashboardShowcase',
    mode: 'light',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Your brand. Every stylist. Every booking.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Rio Blowout Bar',
        headline: 'BOOKINGS. IN ONE RING.',
        rows: [
          { primary: 'Taylor Nguyen',    secondary: 'Cut + color · Saturday 12 PM',       meta: '1:04', status: 'booked', atFrame: 20  },
          { primary: 'Amber Chen',       secondary: 'Blowout · Thursday 5 PM',              meta: '0:48', status: 'booked', atFrame: 120 },
          { primary: 'Grace Kwon',       secondary: 'Wedding party booking · Sat 9 AM',      meta: '2:14', status: 'booked', atFrame: 220 },
          { primary: 'Christina Wu',     secondary: 'Rescheduling · confirmed Sun',           meta: '0:38', status: 'info',   atFrame: 340 },
          { primary: 'Rachel Davis',     secondary: 'New client consult · Wed 3 PM',          meta: '1:32', status: 'lead',   atFrame: 460 },
          { primary: 'Nina Alvarez',     secondary: 'Extension service · Fri 6 PM',            meta: '1:12', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-155-dash-electric-brand',
    seed: 155155,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label AI. Sold under your name.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'Volt & Wire Electric',
        headline: 'CALLS ANSWERED. CLIENTS BOOKED.',
        rows: [
          { primary: 'Kevin Ortiz',      secondary: 'Half-house outage · 5:30 PM',         meta: '1:58', status: 'booked', atFrame: 20  },
          { primary: 'Nina Alvarez',     secondary: 'Panel upgrade · Tue 10 AM',              meta: '1:44', status: 'booked', atFrame: 120 },
          { primary: 'Brian Foster',     secondary: 'Outlet replacement · today 4 PM',        meta: '0:48', status: 'booked', atFrame: 220 },
          { primary: 'Grace Kwon',       secondary: 'Whole-home surge quote · walk-through',    meta: '2:04', status: 'lead',   atFrame: 340 },
          { primary: 'Amber Chen',       secondary: 'Wiring inspection · Fri 9 AM',             meta: '1:22', status: 'booked', atFrame: 460 },
          { primary: 'Priya Kapoor',     secondary: 'EV charger install · info sent',           meta: '1:12', status: 'lead',   atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-156-dash-pest-brand',
    seed: 156156,
    template: 'DashboardShowcase',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Same-day slots booked. Automatically.',
      dashboardShowcase: {
        variant: 'calls',
        surfaceLabel: 'Recent Calls',
        brandName: 'ShieldGuard Pest Control',
        headline: 'SAME-DAY SLOTS. BOOKED.',
        rows: [
          { primary: 'Omar Haddad',    secondary: 'Wasp nest · today 2 PM',              meta: '0:47', status: 'booked', atFrame: 20  },
          { primary: 'Marcus Brown',    secondary: 'Ant treatment · today 4 PM',           meta: '1:12', status: 'booked', atFrame: 120 },
          { primary: 'Rachel Davis',    secondary: 'Rodent inspection · Wed 10 AM',         meta: '1:32', status: 'booked', atFrame: 220 },
          { primary: 'Eleanor Diaz',    secondary: 'Termite quote · Sat walk-through',       meta: '2:04', status: 'lead',   atFrame: 340 },
          { primary: 'Jordan Mills',    secondary: 'Recurring quarterly · Mon 8 AM',         meta: '0:58', status: 'booked', atFrame: 460 },
          { primary: 'Mark Sullivan',   secondary: 'Spider treatment · Thu 3 PM',            meta: '1:04', status: 'booked', atFrame: 580 },
        ],
      },
    },
    cta: 'Start your agency',
  },
];

// ────────────────────────────────────────────────────────────────────────────
// KINETICSTATEMENT — 17 new one-line kinetic reels
// ────────────────────────────────────────────────────────────────────────────
const KINETIC_BATCH: ReelSpec[] = [
  { id: 'reel-160-k-whitelabel-yours', seed: 160160, template: 'KineticStatement', mode: 'dark',  background: 'mesh',      durationInFrames: 510, hook: 'White-label the AI. Sell it as yours.',                       beats: [], options: { emphasisWords: ['yours'],           ctaSubline: 'Your logo. Your dashboard. Your check.' },       cta: 'Start your agency' },
  { id: 'reel-161-k-not-building',      seed: 161161, template: 'KineticStatement', mode: 'dark',  background: 'sweep',     durationInFrames: 480, hook: 'You do not build the AI. You sell it.',                       beats: [], options: { emphasisWords: ['sell'],            ctaSubline: 'The tool is built. The market is waiting.' },       cta: 'Start your agency' },
  { id: 'reel-162-k-your-brand',        seed: 162162, template: 'KineticStatement', mode: 'dark',  background: 'grid',      durationInFrames: 510, hook: 'Your logo. Your dashboard. Your money.',                       beats: [], options: { emphasisWords: ['your'],            ctaSubline: 'White-label everything. Keep the margin.' },        cta: 'Start your agency' },
  { id: 'reel-163-k-every-business',    seed: 163163, template: 'KineticStatement', mode: 'light', background: 'mesh',      durationInFrames: 540, hook: 'Every local business needs a receptionist.',                    beats: [], options: { emphasisWords: ['every'],           ctaSubline: 'Almost none can afford a real one. Sell them AI.' }, cta: 'Start your agency' },
  { id: 'reel-164-k-not-course',        seed: 164164, template: 'KineticStatement', mode: 'dark',  background: 'noise',     durationInFrames: 510, hook: 'This is not a course. This is a platform.',                    beats: [], options: { emphasisWords: ['platform'],        ctaSubline: 'No courses. No upsells. No guru nonsense.' },       cta: 'Start your agency' },
  { id: 'reel-165-k-answer-books',      seed: 165165, template: 'KineticStatement', mode: 'dark',  background: 'particles', durationInFrames: 510, hook: 'The AI answers. You collect.',                                   beats: [], options: { emphasisWords: ['collect'],          ctaSubline: 'The AI does the calls. You do the closing.' },       cta: 'Start your agency' },
  { id: 'reel-166-k-real-service',       seed: 166166, template: 'KineticStatement', mode: 'dark',  background: 'mesh',      durationInFrames: 540, hook: 'This is a real service business. With real margins.',            beats: [], options: { emphasisWords: ['real'],            ctaSubline: 'Not passive income. Not magic. Just software you sell.' }, cta: 'Start your agency' },
  { id: 'reel-167-k-not-cold-calls',    seed: 167167, template: 'KineticStatement', mode: 'dark',  background: 'tron',      durationInFrames: 510, hook: 'No cold calls. No cold emails. Just clients.',                   beats: [], options: { emphasisWords: ['clients'],          ctaSubline: 'The infrastructure is done. Your job is to sell it.' }, cta: 'Start your agency' },
  { id: 'reel-168-k-brand-everywhere',  seed: 168168, template: 'KineticStatement', mode: 'dark',  background: 'sweep',     durationInFrames: 510, hook: 'Your brand on every call. Every text. Every screen.',            beats: [], options: { emphasisWords: ['brand'],           ctaSubline: 'White-label everything. Keep the margin.' },        cta: 'Start your agency' },
  { id: 'reel-169-k-friday-agency',     seed: 169169, template: 'KineticStatement', mode: 'dark',  background: 'grid',      durationInFrames: 510, hook: 'Start an AI agency by Friday.',                                    beats: [], options: { emphasisWords: ['friday'],           ctaSubline: 'Pick a brand. Pick a plan. Go.' },                cta: 'Start your agency' },
  { id: 'reel-170-k-tool-exists',       seed: 170170, template: 'KineticStatement', mode: 'light', background: 'sweep',     durationInFrames: 510, hook: 'The tool exists. Sell it under your name.',                       beats: [], options: { emphasisWords: ['sell'],            ctaSubline: 'Not another AI wrapper. Your business.' },         cta: 'Start your agency' },
  { id: 'reel-171-k-recurring',          seed: 171171, template: 'KineticStatement', mode: 'dark',  background: 'mesh',      durationInFrames: 510, hook: 'Local businesses. Recurring revenue. Your agency.',               beats: [], options: { emphasisWords: ['recurring'],       ctaSubline: 'Every month. Every client. Your check.' },        cta: 'Start your agency' },
  { id: 'reel-172-k-agency-not-tech',    seed: 172172, template: 'KineticStatement', mode: 'dark',  background: 'noise',     durationInFrames: 480, hook: 'You are not the tech. You are the agency.',                       beats: [], options: { emphasisWords: ['agency'],          ctaSubline: 'The platform does the work. You do the selling.' }, cta: 'Start your agency' },
  { id: 'reel-173-k-answer-missed',      seed: 173173, template: 'KineticStatement', mode: 'dark',  background: 'particles', durationInFrames: 510, hook: 'Answer every call your clients miss.',                            beats: [], options: { emphasisWords: ['every'],           ctaSubline: 'One ring. AI books. Text sent.' },                cta: 'Start your agency' },
  { id: 'reel-174-k-not-magic',          seed: 174174, template: 'KineticStatement', mode: 'dark',  background: 'grid',      durationInFrames: 480, hook: 'Not passive. Not magic. Just software you sell.',                 beats: [], options: { emphasisWords: ['sell'],            ctaSubline: 'A real service business. With real margins.' },   cta: 'Start your agency' },
  { id: 'reel-175-k-you-do-selling',     seed: 175175, template: 'KineticStatement', mode: 'dark',  background: 'sweep',     durationInFrames: 510, hook: 'The AI does the talking. You do the selling.',                    beats: [], options: { emphasisWords: ['selling'],         ctaSubline: 'White-label. Recurring revenue. Your name on it.' },  cta: 'Start your agency' },
  { id: 'reel-176-k-one-platform',       seed: 176176, template: 'KineticStatement', mode: 'light', background: 'grid',      durationInFrames: 540, hook: 'One platform. Every industry. Your brand on it.',                 beats: [], options: { emphasisWords: ['every'],           ctaSubline: 'Sold by you. Answered by AI.' },                  cta: 'Start your agency' },
];

// ────────────────────────────────────────────────────────────────────────────
// STATEMENTSTACK — 13 new triple-claim stacks
// ────────────────────────────────────────────────────────────────────────────
const STACK_BATCH: ReelSpec[] = [
  {
    id: 'reel-180-stack-whole-business',
    seed: 180180,
    template: 'StatementStack',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'A real business. Not a course. Not a guru.',
      statements: [
        { text: 'You pick the brand.',    emphasis: ['brand'] },
        { text: 'You pick the clients.',  emphasis: ['clients'] },
        { text: 'You keep the margin.',   emphasis: ['margin'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-181-stack-whitelabel',
    seed: 181181,
    template: 'StatementStack',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'One brand. Every touchpoint. Every dollar.',
      statements: [
        { text: 'Their calls are your calls.',           emphasis: ['your'] },
        { text: 'Their dashboard is your dashboard.',    emphasis: ['your'] },
        { text: 'Their check is your check.',            emphasis: ['your'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-182-stack-not-course',
    seed: 182182,
    template: 'StatementStack',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Not a course. Not a guru. A platform.',
      statements: [
        { text: 'No course to buy.',           emphasis: ['no'] },
        { text: 'No upsell to survive.',        emphasis: ['no'] },
        { text: 'Just a platform to sell.',     emphasis: ['sell'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-183-stack-what-ai-does',
    seed: 183183,
    template: 'StatementStack',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'The AI does the work. You do the selling.',
      statements: [
        { text: 'The AI answers the phone.',         emphasis: ['AI'] },
        { text: 'The AI books the appointment.',      emphasis: ['AI'] },
        { text: 'You collect the fee.',                 emphasis: ['You'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-184-stack-three-pieces',
    seed: 184184,
    template: 'StatementStack',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label everything. Keep the margin.',
      statements: [
        { text: 'One brand. Yours.',        emphasis: ['yours'] },
        { text: 'One dashboard. Yours.',     emphasis: ['yours'] },
        { text: 'One margin. Yours.',        emphasis: ['yours'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-185-stack-speed',
    seed: 185185,
    template: 'StatementStack',
    mode: 'dark',
    background: 'tron',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Set up by Sunday. Selling by Monday.',
      statements: [
        { text: 'Set it up in a day.',         emphasis: ['day'] },
        { text: 'Land a client in a week.',    emphasis: ['client'] },
        { text: 'Get paid every month.',       emphasis: ['paid'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-186-stack-why-now',
    seed: 186186,
    template: 'StatementStack',
    mode: 'light',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'The infrastructure is built. Your job is to sell it.',
      statements: [
        { text: 'The tool exists.',        emphasis: ['exists'] },
        { text: 'The market exists.',       emphasis: ['exists'] },
        { text: 'You do the connecting.',   emphasis: ['You'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-187-stack-not-tech',
    seed: 187187,
    template: 'StatementStack',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'The AI is the product. You are the business.',
      statements: [
        { text: 'You are not the tech.',      emphasis: ['not'] },
        { text: 'You are not the AI.',         emphasis: ['not'] },
        { text: 'You are the agency.',         emphasis: ['agency'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-188-stack-recurring',
    seed: 188188,
    template: 'StatementStack',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Local businesses. Every month. Your check.',
      statements: [
        { text: 'Not a one-time sale.',    emphasis: ['not'] },
        { text: 'Not a project fee.',       emphasis: ['not'] },
        { text: 'Every month. Every client.', emphasis: ['every'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-189-stack-offer',
    seed: 189189,
    template: 'StatementStack',
    mode: 'dark',
    background: 'mesh',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'The tools are built. Sell them under your brand.',
      statements: [
        { text: 'The AI is built.',                  emphasis: ['built'] },
        { text: 'The dashboard is built.',            emphasis: ['built'] },
        { text: 'Your job is to sell it.',            emphasis: ['sell'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-190-stack-white-label-all',
    seed: 190190,
    template: 'StatementStack',
    mode: 'light',
    background: 'grid',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'White-label the whole stack. Sold by you.',
      statements: [
        { text: 'Your logo on the call.',       emphasis: ['your'] },
        { text: 'Your name on the dashboard.',   emphasis: ['your'] },
        { text: 'Your name on the invoice.',     emphasis: ['your'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-191-stack-anti-guru',
    seed: 191191,
    template: 'StatementStack',
    mode: 'dark',
    background: 'noise',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Not a guru pitch. A real service business.',
      statements: [
        { text: 'This is not a get-rich.',        emphasis: ['not'] },
        { text: 'This is not passive income.',     emphasis: ['not'] },
        { text: 'This is a real service business.', emphasis: ['real'] },
      ],
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-192-stack-flip',
    seed: 192192,
    template: 'StatementStack',
    mode: 'dark',
    background: 'particles',
    durationInFrames: 900,
    hook: '', beats: [],
    options: {
      ctaSubline: 'Pick a brand. Pick a plan. Sell it.',
      statements: [
        { text: 'You pick the brand.',       emphasis: ['brand'] },
        { text: 'The AI answers the phone.',  emphasis: ['AI'] },
        { text: 'You take the check.',        emphasis: ['check'] },
      ],
    },
    cta: 'Start your agency',
  },
];

// ────────────────────────────────────────────────────────────────────────────
// PRODUCTDEMO — 2 new CallModal industry variants
// ────────────────────────────────────────────────────────────────────────────
const PRODUCTDEMO_BATCH: ReelSpec[] = [
  {
    id: 'reel-200-pd-hvac',
    seed: 200200,
    template: 'ProductDemo',
    mode: 'dark',
    background: 'grid',
    durationInFrames: 900,
    kicker: 'live AI call · white-label for your agency',
    hook: 'One ring. AI dispatches.',
    beats: [],
    options: {
      ctaSubline: 'One platform. Every industry. Your brand on it.',
      callScript: {
        clientName: 'AAA Heating & Cooling',
        connectingStart: 60,
        liveStart: 130,
        endedStart: 740,
        bookingStart: 660,
        bookingMessage: 'Today · 11:00 AM · Tech dispatched · Confirmation sent',
        transcript: [
          { id: 't1', role: 'assistant', text: 'Hi, AAA Heating and Cooling. How can I help?',           startFrame: 165 },
          { id: 't2', role: 'user',      text: 'My furnace stopped working last night, house is cold.',   startFrame: 270 },
          { id: 't3', role: 'assistant', text: 'I can dispatch a tech for 11 AM today. Address please?',   startFrame: 365 },
          { id: 't4', role: 'user',      text: '812 Linden Drive.',                                        startFrame: 485 },
          { id: 't5', role: 'assistant', text: 'Booked. Tech on the way. Confirmation on its way.',        startFrame: 555 },
        ],
        events: [
          { id: 'e1', type: 'dialing',      message: 'Calling AAA Heating & Cooling…', level: 'info',    atFrame: 65  },
          { id: 'e2', type: 'call-start',   message: 'Call connected',                  level: 'success', atFrame: 130 },
          { id: 'e3', type: 'speech-start', message: 'Assistant speaking',              level: 'info',    atFrame: 170 },
          { id: 'e4', type: 'transcript',   message: 'Final transcript received',        level: 'info',    atFrame: 230 },
          { id: 'e5', type: 'speech-start', message: 'Assistant speaking',              level: 'info',    atFrame: 370 },
          { id: 'e6', type: 'transcript',   message: 'Final transcript received',        level: 'info',    atFrame: 515 },
          { id: 'e7', type: 'tool-call',    message: 'Tool: dispatch_technician',       level: 'info',    atFrame: 600 },
          { id: 'e8', type: 'booking',      message: 'Tech dispatched · 11 AM',          level: 'success', atFrame: 645 },
          { id: 'e9', type: 'call-end',     message: 'Call ended',                       level: 'info',    atFrame: 745 },
        ],
      },
    },
    cta: 'Start your agency',
  },
  {
    id: 'reel-201-pd-salon',
    seed: 201201,
    template: 'ProductDemo',
    mode: 'dark',
    background: 'sweep',
    durationInFrames: 900,
    kicker: 'live AI call · white-label for your agency',
    hook: 'One ring. AI books.',
    beats: [],
    options: {
      ctaSubline: 'White-label. Every industry. Your brand.',
      callScript: {
        clientName: 'Rio Blowout Bar',
        connectingStart: 60,
        liveStart: 130,
        endedStart: 740,
        bookingStart: 660,
        bookingMessage: 'Saturday · 12:00 PM · Cut + color · Confirmation sent',
        transcript: [
          { id: 't1', role: 'assistant', text: 'Hi, Rio Blowout Bar. How can I help?',                startFrame: 165 },
          { id: 't2', role: 'user',      text: 'I want a cut and color with Rio if she is available.', startFrame: 270 },
          { id: 't3', role: 'assistant', text: 'Rio is open Saturday at 12 PM. Does that work?',        startFrame: 365 },
          { id: 't4', role: 'user',      text: 'Yeah, book it.',                                        startFrame: 485 },
          { id: 't5', role: 'assistant', text: 'Booked. Reminder will go out the day before.',           startFrame: 555 },
        ],
        events: [
          { id: 'e1', type: 'dialing',      message: 'Calling Rio Blowout Bar…',   level: 'info',    atFrame: 65  },
          { id: 'e2', type: 'call-start',   message: 'Call connected',              level: 'success', atFrame: 130 },
          { id: 'e3', type: 'speech-start', message: 'Assistant speaking',           level: 'info',    atFrame: 170 },
          { id: 'e4', type: 'transcript',   message: 'Final transcript received',    level: 'info',    atFrame: 230 },
          { id: 'e5', type: 'speech-start', message: 'Assistant speaking',           level: 'info',    atFrame: 370 },
          { id: 'e6', type: 'transcript',   message: 'Final transcript received',    level: 'info',    atFrame: 515 },
          { id: 'e7', type: 'tool-call',    message: 'Tool: book_appointment',      level: 'info',    atFrame: 600 },
          { id: 'e8', type: 'booking',      message: 'Booked · Saturday 12 PM',      level: 'success', atFrame: 645 },
          { id: 'e9', type: 'call-end',     message: 'Call ended',                   level: 'info',    atFrame: 745 },
        ],
      },
    },
    cta: 'Start your agency',
  },
];

export const BATCH_002: ReelSpec[] = [
  ...CALLFLOW_BATCH,
  ...BEFOREAFTER_BATCH,
  ...DASHBOARD_BATCH,
  ...KINETIC_BATCH,
  ...STACK_BATCH,
  ...PRODUCTDEMO_BATCH,
];
